language: csharp
solution: src/FbMessengerSdk.sln
mono: none
dotnet: 2.1.402
script:
 - dotnet build src/FbMessengerSdk.sln

deploy:
  skip_cleanup: true
  provider: script
  script:
   - dotnet pack src/FbMessenger.Messaging/FbMessenger.Messaging.csproj --no-build /p:PackageVersion=0.1.0 --version-suffix "dev-$TRAVIS_BUILD_NUMBER"
   - dotnet nuget push src/FbMessenger.Messaging/bin/Release/FbMessenger.Messaging.*.nupkg --api-key $NUGET_API_KEY --source $NUGET_SOURCE
  on:
    branch: master
 
