language: csharp
mono: none
dotnet: 2.1.402
script:
 - dotnet build src/FbMessengerSdk.sln -p:Version="0.1.0.$TRAVIS_BUILD_NUMBER" --configuration Release 

deploy:
  - provider: script
    skip_cleanup: true
    script:
    - dotnet pack /property:PackageVersion="0.1.0-dev-$TRAVIS_BUILD_NUMBER" --configuration Release --no-build src/FbMessenger.Messaging/FbMessenger.Messaging.csproj && dotnet nuget push src/FbMessenger.Messaging/bin/Release/FbMessenger.Messaging.*.nupkg --api-key $NUGET_API_KEY --source $NUGET_SOURCE
    on:
      branch: dev
  - provider: script
    skip_cleanup: true
    script:
    - dotnet pack /property:PackageVersion="0.1.0-dev-$TRAVIS_BUILD_NUMBER" --configuration Release --no-build src/FbMessenger.WebhookEvents/FbMessenger.WebhookEvents.csproj && dotnet nuget push src/FbMessenger.WebhookEvents/bin/Release/FbMessenger.WebhookEvents.*.nupkg --api-key $NUGET_API_KEY --source $NUGET_SOURCE
    on:
      branch: dev
  - provider: script
    skip_cleanup: true
    script:
    - dotnet pack /property:PackageVersion="$TRAVIS_TAG" --configuration Release --no-build src/FbMessenger.Messaging/FbMessenger.Messaging.csproj && dotnet nuget push src/FbMessenger.Messaging/bin/Release/FbMessenger.Messaging.*.nupkg --api-key $NUGET_API_KEY --source $NUGET_SOURCE
    on:
      branch: master
      tags: true
  - provider: script
    skip_cleanup: true
    script:
    - dotnet pack /property:PackageVersion="$TRAVIS_TAG" --configuration Release --no-build src/FbMessenger.WebhookEvents/FbMessenger.WebhookEvents.csproj && dotnet nuget push src/FbMessenger.WebhookEvents/bin/Release/FbMessenger.WebhookEvents.*.nupkg --api-key $NUGET_API_KEY --source $NUGET_SOURCE
    on:
      branch: master
      tags: true
